[build]
builder = "nixpacks"
buildCommand = "cd ClassManagerBackEndSpringBoot && mvn clean compile"

[deploy]
startCommand = "cd ClassManagerBackEndSpringBoot && mvn spring-boot:run"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Especificar versión de Java
[phases.setup]
nixPkgs = ["openjdk17", "maven"]
